import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

import '../../../core/money/money.dart';
import '../../../domain/models.dart';
import '../../../shared/pdf/galla_pdf_fonts.dart';

class PdfExport {
  static Future<void> shareReport({
    required SimpleReport report,
    required String businessName,
    required String currency,
  }) async {
    final doc = await GallaPdfFonts.createDocument();
    String m(int v) => Money(v, currency: currency).format();
    doc.addPage(
      // MultiPage so long histories never overflow a single sheet.
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        build: (context) {
          return [
            pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(
                  businessName.isEmpty ? 'Galla' : businessName,
                  style: pw.TextStyle(
                    fontSize: 22,
                    fontWeight: pw.FontWeight.bold,
                  ),
                ),
                pw.SizedBox(height: 4),
                pw.Text('Simple report · ${report.period.label}'),
                pw.Text(
                  '${DateFormat.yMMMd().format(report.period.start)} – ${DateFormat.yMMMd().format(report.period.end.subtract(const Duration(days: 1)))}',
                ),
                pw.SizedBox(height: 24),
                _row('Money in', m(report.moneyInMinor)),
                _row('Money out', m(report.moneyOutMinor)),
                _row("What's left", m(report.leftMinor)),
                pw.Divider(),
                _row('Cash in', m(report.cashInMinor)),
                _row('Cash out', m(report.cashOutMinor)),
                _row('Udhaar given', m(report.udhaarGivenMinor)),
                _row('Udhaar taken', m(report.udhaarTakenMinor)),
                if (report.taxMinor > 0)
                  _row('Estimated tax', m(report.taxMinor)),
              ],
            ),
          ];
        },
        footer: (context) => pw.Text(
          'Generated by Galla. Figures come from recorded entries. This is not a tax filing.',
          style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey700),
        ),
      ),
    );
    await Printing.sharePdf(
      bytes: await doc.save(),
      filename: 'galla-report.pdf',
    );
  }

  static pw.Widget _row(String label, String value) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 6),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(label, style: const pw.TextStyle(fontSize: 14)),
          pw.Text(
            value,
            style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold),
          ),
        ],
      ),
    );
  }
}
