import 'dart:typed_data';

import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

import '../../../core/money/money.dart';
import '../../../domain/models.dart';

class PdfExport {
  static Future<void> shareReport({
    required SimpleReport report,
    required String businessName,
    required String currency,
  }) async {
    final doc = pw.Document();
    String m(int v) => Money(v, currency: currency).format();
    doc.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(businessName.isEmpty ? 'Galla' : businessName,
                  style: pw.TextStyle(fontSize: 22, fontWeight: pw.FontWeight.bold)),
              pw.SizedBox(height: 4),
              pw.Text('Simple report · ${report.period.label}'),
              pw.Text(
                '${DateFormat.yMMMd().format(report.period.start)} – ${DateFormat.yMMMd().format(report.period.end.subtract(const Duration(days: 1)))}',
              ),
              pw.SizedBox(height: 24),
              _row('Money in', m(report.moneyInMinor)),
              _row('Money out', m(report.moneyOutMinor)),
              _row("What's left", m(report.leftMinor)),
              pw.Divider(),
              _row('Cash in', m(report.cashInMinor)),
              _row('Cash out', m(report.cashOutMinor)),
              _row('Udhaar given', m(report.udhaarGivenMinor)),
              _row('Udhaar taken', m(report.udhaarTakenMinor)),
              if (report.taxMinor > 0) _row('Estimated tax', m(report.taxMinor)),
              pw.Spacer(),
              pw.Text(
                'Generated by Galla. Figures come from recorded entries. This is not a tax filing.',
                style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey700),
              ),
            ],
          );
        },
      ),
    );
    await Printing.sharePdf(bytes: await doc.save(), filename: 'galla-report.pdf');
  }

  static Future<Uint8List> partyStatementBytes({
    required Party party,
    required List<Txn> history,
    required String businessName,
    required String currency,
    required String theyOweYou,
    required String youOweThem,
    required String settled,
  }) async {
    final doc = pw.Document();
    String m(int v) => Money(v, currency: currency).format();
    final balanceLabel = party.balanceMinor == 0
        ? settled
        : party.balanceMinor > 0
            ? theyOweYou
            : youOweThem;
    doc.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(businessName.isEmpty ? 'Galla' : businessName,
                  style: pw.TextStyle(fontSize: 20, fontWeight: pw.FontWeight.bold)),
              pw.SizedBox(height: 8),
              pw.Text('Statement for ${party.name}',
                  style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
              pw.Text('$balanceLabel: ${m(party.balanceMinor.abs())}'),
              pw.SizedBox(height: 16),
              pw.TableHelper.fromTextArray(
                headers: ['Date', 'In / Out', 'Note', 'Amount'],
                data: history.map((t) {
                  return [
                    DateFormat.yMMMd().format(t.occurredAt),
                    t.direction == Direction.moneyIn ? 'In' : 'Out',
                    [
                      if (t.isCredit) 'Udhaar',
                      t.note ?? t.category ?? '',
                    ].join(' '),
                    m(t.amountMinor),
                  ];
                }).toList(),
              ),
            ],
          );
        },
      ),
    );
    return doc.save();
  }

  static pw.Widget _row(String label, String value) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 6),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(label, style: const pw.TextStyle(fontSize: 14)),
          pw.Text(value, style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
        ],
      ),
    );
  }
}
